language: node_js
node_js: '12'

# Travis CI 서버의 Home
cache:
  directories:
    - '${HOME}/.cache/yarn' #캐시 디렉토리

# before_install:
#   - npm install -g yarn@1.21.1

# install: true // yarn install 스킵. 노드모듈을 생성안함.

script:
- echo "skipping tests" #테스트를 스킵함

before_deploy:
  - CI=false npm run build
  

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: jaehoon-dayoff.ml # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: build #build폴더의 내용물만 업로드.
    wait-until-deployed: true
    on:
      repo: hoonsbory/dayoff-react #Github 주소
      branch: master


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tonymkcv93@gmail.com 